# Generated by Django 3.1.4 on 2020-12-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_number', models.CharField(max_length=8, null=True, unique=True)),
                ('first_names', models.TextField()),
                ('last_names', models.TextField()),
            ],
            options={
                'unique_together': {('first_names', 'last_names')},
            },
        ),
    ]
