# Generated by Django 3.1.4 on 2020-12-27 13:52

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations
from django.contrib.postgres.search import SearchVector


def update_full_search(apps, schema_editor):
    model = apps.get_model('votes', 'Person')
    model.objects.update(
        full_search=SearchVector(
            'dni_number', 'strApellidoPaterno', 'strApellidoMaterno',
            'strNombres',
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0004_auto_20201227_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='full_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='person',
            index=django.contrib.postgres.indexes.GinIndex(fields=['full_search'],
                                                           name='full_search_idx'),
        ),
        migrations.RunPython(
            update_full_search, reverse_code=migrations.RunPython.noop
        ),
    ]
