# Generated by Django 3.1.4 on 2020-12-27 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0005_auto_20201227_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompiledPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso_total', models.IntegerField(null=True)),
                ('ingreso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='votes.ingresos')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='votes.person')),
            ],
        ),
    ]
