# Generated by Django 3.1.4 on 2020-12-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0006_compiledperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='compiledperson',
            name='inmuebles',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='compiledperson',
            name='muebles',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='compiledperson',
            name='total_muebles_inmuebles',
            field=models.IntegerField(null=True),
        ),
    ]
