# Generated by Django 3.1.4 on 2020-12-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0007_auto_20201228_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='compiledperson',
            name='sentencias_obliga',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='compiledperson',
            name='sentencias_penales',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='compiledperson',
            name='sentencias_total',
            field=models.IntegerField(null=True),
        ),
    ]
