# Generated by Django 3.1.4 on 2020-12-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0008_auto_20201228_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_names',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_names',
            field=models.TextField(null=True),
        ),
    ]
