# Generated by Django 3.1.4 on 2020-12-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0010_auto_20201230_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='idOrganizacionPolitica',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
