# Generated by Django 3.1.4 on 2020-12-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0011_auto_20201230_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='compiledperson',
            name='tweeted',
            field=models.BooleanField(default=False),
        ),
    ]
